[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
lapin = "2.1"
influxdb = { version = "0.5", features = ["derive"] }
yellowstone-grpc-client = "1.15.2"
yellowstone-grpc-proto = "=1.14.2"
chrono = "*"
subtle = "=2.4.1"
bs58 = "*"
tonic = { version = "*", features = ["tls"] }
anyhow = "1.0.86"
solana-sdk = "2.0.7"
futures = "0.3.30"
hex = "0.4.3"
